Repository Talus-Network/nexus-sdk, pull requests merged in 2025-04, with the labels that each got.

#131 fix: remove token for gitbook-docs which is public in sync docs workflow
  .github/workflows/sync_docs.yml
Labels: bug, documentation

#134 chore: update sap to tap in docs + add PAT to sync docs workflow + sync with gitbook
  .github/workflows/sync_docs.yml
  docs/CLI.md
  docs/guides/llm-openai-chat-prep-tool.md
  docs/guides/math-branching-dag-builder.md
  docs/guides/math-branching-quickstart.md
  docs/index.md
Labels: documentation

#136 docs: fix links and make syntax consistent
  docs/CLI.md
  docs/guides/math-branching-dag-builder.md
  docs/guides/math-branching-quickstart.md
  docs/guides/math_branching-dag-entry.md
  docs/guides/math_branching_with_chat.md
  docs/guides/setup.md
  docs/index.md
  docs/tool-development.md
  docs/toolkit-rust.md
Labels: documentation

#139 docs: update access information about the Sui Explorer
  docs/guides/setup.md
Labels: documentation

#49 [nexus-tool] social tool batch #1 (twitter api v2)
  tools/social-twitter/Cargo.toml
  tools/social-twitter/README.md
  tools/social-twitter/src/auth.rs
  tools/social-twitter/src/error.rs
  tools/social-twitter/src/list/add_member.rs
  tools/social-twitter/src/list/create_list.rs
  tools/social-twitter/src/list/get_list.rs
  tools/social-twitter/src/list/get_list_members.rs
  tools/social-twitter/src/list/get_list_tweets.rs
  tools/social-twitter/src/list/mod.rs
  tools/social-twitter/src/list/models.rs
  tools/social-twitter/src/list/remove_member.rs
  tools/social-twitter/src/list/update_list.rs
  tools/social-twitter/src/main.rs
  tools/social-twitter/src/tweet/get_mentioned_tweets.rs
  tools/social-twitter/src/tweet/get_tweet.rs
  tools/social-twitter/src/tweet/get_user_tweets.rs
  tools/social-twitter/src/tweet/like_tweet.rs
  tools/social-twitter/src/tweet/mod.rs
  tools/social-twitter/src/tweet/models.rs
  tools/social-twitter/src/tweet/post_tweet.rs
  tools/social-twitter/src/user/get_user_by_id.rs
  tools/social-twitter/src/user/get_user_by_username.rs
  tools/social-twitter/src/user/mod.rs
  tools/social-twitter/src/user/models.rs
Labels: enhancement, nexus-tool

#146 docs: implement review comments
  .github/workflows/sync_docs.yml
  docs/guides/llm-openai-chat-prep-tool.md
  docs/guides/math-branching-dag-builder.md
  docs/guides/math-branching-dag-entry.md
  docs/guides/math-branching-quickstart.md
  docs/guides/math-branching-with-chat.md
  docs/guides/setup.md
Labels: documentation
